### ISSUE TITLE
Stackoverflow Error

### ISSUE THREAD

**Issue by amitjoy** [Scalified/tree#6]
Even though I don't have any edge to itself, I still encountered StackOverFlowError.

Version: 0.2.5

```java
Exception in thread "main" java.lang.StackOverflowError
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at com.scalified.tree.TreeNode$4.perform(TreeNode.java:762)
	at com.scalified.tree.multinode.ArrayMultiTreeNode.traversePreOrder(ArrayMultiTreeNode.java:414)
	at com.scalified.tree.multinode.ArrayMultiTreeNode.traversePreOrder(ArrayMultiTreeNode.java:418)
	at com.scalified.tree.multinode.ArrayMultiTreeNode.traversePreOrder(ArrayMultiTreeNode.java:418)
	at com.scalified.tree.multinode.ArrayMultiTreeNode.traversePreOrder(ArrayMultiTreeNode.java:418)
	at com.scalified.tree.multinode.ArrayMultiTreeNode.traversePreOrder(ArrayMultiTreeNode.java:418)
	at com.scalified.tree.multinode.ArrayMultiTreeNode.traversePreOrder(ArrayMultiTreeNode.java:418)
	at com.scalified.tree.multinode.ArrayMultiTreeNode.traversePreOrder(ArrayMultiTreeNode.java:418)
	at com.scalified.tree.multinode.ArrayMultiTreeNode.traversePreOrder(ArrayMultiTreeNode.java:418)
	at com.scalified.tree.multinode.ArrayMultiTreeNode.traversePreOrder(ArrayMultiTreeNode.java:418)
```

**Comment by vbaidak** [comment]
@amitjoy , please provide the code snippet including tree declaration and operations you are trying to perform, so that I can execute it.

Thanks!
